### ISSUE TITLE
Enhanced materialized view in CBDB

### ISSUE THREAD

**Issue by my-ship-it** [cloudberrydb/cloudberrydb#105]
We need to enhance materialized view in CBDB:

```
Automatically refresh mt view instead of manually.
Incremental refresh mt view.
Results reuse for mt view by planner
```

**Comment by avamingli** [comment]
https://github.com/orgs/cloudberrydb/discussions/36 IVM general summary

**Comment by avamingli** [comment]
### Articles
[Optimizing Queries Using Materialized Views: A Practical, Scalable Solution](https://courses.cs.washington.edu/courses/cse591d/01sp/opt_views.pdf)

**Comment by avamingli** [comment]
[Automated Selection of Materialized Views and Indexes for SQL Databases](https://www.vldb.org/conf/2000/P496.pdf)

**Comment by my-ship-it** [comment]
Already supported
