### ISSUE TITLE
SQL editor support

### ISSUE THREAD

**Issue by my-ship-it** [cloudberrydb/cloudberrydb#125]

**Comment by Aizwe** [comment]
pgweb的阅读和sqleditor的接口设计：https://hashdata.feishu.cn/docx/POv6dvBGWoZQcCxPUrlcCLcJndd

**Comment by vvfreesoul** [comment]
pgweb的阅读报告和sqleditor的接口设计：https://github.com/cloudberrydb/cloudberrydb/issues/125

**Comment by tuhaihe** [comment]
Hi @vvfreesoul, Is it possible to provide internet access to the Feishu document if it can be made public?

**Comment by my-ship-it** [comment]
Already done
