### ISSUE TITLE
[Enhance] Too many log messages for memory stats when run out of memory

### ISSUE THREAD

**Issue by gfphoenix78** [cloudberrydb/cloudberrydb#159]
### Cloudberry Database version

1.3, perhaps all versions have this issue.

### What happened

When a query causes out of memory, it may call `RunawayCleaner_RunawayCleanupDoneForProcess`. This function will dump all memory stats from TopMemoryContext to its descendant. The log message may be huge, up to tens giga bytes. It looks dangerous that may cause out of disk for the cluster.

### How to reproduce

skip.

### Operating System

centos

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by my-ship-it** [comment]
No reproducible steps provided.
