### ISSUE TITLE
to_date: ERROR:  date/time field value out of range: "20031301"

### ISSUE THREAD

**Issue by liyxbeijing** [cloudberrydb/cloudberrydb#193]
### Cloudberry Database version

version                                                         
                                                   
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------
 PostgreSQL 14.4 (Cloudberry Database 1.4.0 build commit:e83e3ffc22d538deb2dbceeeae0138ca2de064e6) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.1 20210130 (Red Hat 1
0.2.1-11), 64-bit compiled on Aug  3 2023 10:15:47
(1 row)

### What happened

function to_date in cbdb got below errors:

```
dw_open=# select to_date('20031301','yyyymmdd');
ERROR:  date/time field value out of range: "20031301"
dw_open=# 
```

but same function works in hashdata 2.x:

```
dw_open=# select to_date('20031301','yyyymmdd');
  to_date   
------------
 2004-01-01
(1 row)

```

### How to reproduce

run: select to_date('20031301','yyyymmdd');

### Operating System

centos 7.9

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by lss602726449** [comment]
This is bug in hashdata 2.x. We test hash3.x, CBDB, PG14.4, all these  output with 'ERROR:  date/time field value out of range: "20031301"'. Also this make on sense that one year has more than 12 months.
