### ISSUE TITLE
[Bug] gpinitsystem failed with missing library.

### ISSUE THREAD

**Issue by RyanWei** [cloudberrydb/cloudberrydb#194]
### Cloudberry Database version

cloudberry-db-1.4.0-1.el7.aarch64.rpm

### What happened

I've installed CBDB bianry with 
yum install -y /tmp/cloudberry-db-1.4.0-1.el7.aarch64.rpm

When try to run gpinitsystem I met following error:

2023-09-07 17:37:37.339676 CST,,,p4957,th-1550045184,,,,746,,cmd979,seg-10000,,,x746,sx1,"FATAL","XX000","could not load library ""/usr/local/cloudberry-db-1.4.0/lib/postgresql/quicklz_compressor.so"": libquicklz.so: cannot open shared object file: No such file or directory",,,,,,"
-- EOF
RESET ALL;
CREATE FUNCTION gp_quicklz_constructor(internal, internal, bool) RETURNS internal
LANGUAGE C VOLATILE AS '$libdir/quicklz_compressor.so', 'quicklz_constructor';
COMMENT ON FUNCTION gp_quicklz_constructor(internal, internal, bool) is 'quicklz constructor';
",,"internal_load_library","dfmgr.c",246,1    0xcb54ec postgres errstart (elog.c:579)
2    0xcbc0f0 postgres <symbol not found> (dfmgr.c:246)
3    0xcbc618 postgres load_external_function (dfmgr.c:122)
4    0x7fb8b4 postgres fmgr_c_validator (discriminator 5)
5    0xcbe31c postgres OidFunctionCall1Coll (fmgr.c:1143)
6    0x7fb0fc postgres ProcedureCreate (pg_proc.c:783)
7    0x899674 postgres CreateFunction (discriminator 8)
8    0xb3c9a0 postgres <symbol not found> (utility.c:2038)
9    0xb3b400 postgres standard_ProcessUtility (utility.c:1270)
10   0xb388f4 postgres <symbol not found> (palloc.h:172)
11   0xb38e10 postgres <symbol not found> (pquery.c:1515)
12   0xb3a284 postgres PortalRun (pquery.c:970)
13   0xb34e8c postgres <symbol not found> (postgres.c:1940)
14   0xb377e4 postgres PostgresMain (postgres.c:5573)
15   0x6c23a0 postgres main (main.c:205)
16   0xffffa4142724 libc.so.6 __libc_start_main + 0xf0
17   0x6d1724 postgres <symbol not found> + 0x6d1724

Seems libquicklz.so is not installed, I don't need to use qucklz as compression method, how to bypass this issue?

### How to reproduce

yum install -y /tmp/cloudberry-db-1.4.0-1.el7.aarch64.rpm

gpinitsystem

### Operating System

[root@mdw tmp]# cat /etc/os-release NAME="CentOS Linux" VERSION="7 (AltArch)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (AltArch)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7:server" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"  CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by RyanWei** [comment]
I've compared x86 version and arm version, the library exists in x86 binary however NOT found in arm version.

X86 binary (cloudberry-db-1.4.0-1.el7.centos.x86_64.rpm)

[root@i-jj075kh1 lib]# ls -l /usr/local/cloudberry-db/lib/libquicklz*
lrwxrwxrwx 1 root root    19 Sep  8 09:53 /usr/local/cloudberry-db/lib/libquicklz.so -> libquicklz.so.1.5.0
lrwxrwxrwx 1 root root    19 Sep  8 09:53 /usr/local/cloudberry-db/lib/libquicklz.so.1 -> libquicklz.so.1.5.0
-rwxr-xr-x 1 root root 19256 Aug  3 10:21 /usr/local/cloudberry-db/lib/libquicklz.so.1.5.0

Arm binary (cloudberry-db-1.4.0-1.el7.aarch64.rpm)

[root@mdw /]# ls -l /usr/local/cloudberry-db/lib/libquicklz*
ls: cannot access /usr/local/cloudberry-db/lib/libquicklz*: No such file or directory

**Comment by my-ship-it** [comment]
Already fixed in next release
