### ISSUE TITLE
[Bug] icw test fail on parallel_is_better case in gp_parallel

### ISSUE THREAD

**Issue by smartyhero** [cloudberrydb/cloudberrydb#241]
### Cloudberry Database version

branch:  main
commit id : b692345b 

### What happened

trigger build cloudberrydb, build success, but icw test is failed

case name:  gp_parallel

log :
```
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /code/gpdb_src/src/test/regress/expected/gp_parallel.out /code/gpdb_src/src/test/regress/results/gp_parallel.out
--- /code/gpdb_src/src/test/regress/expected/gp_parallel.out	2023-10-18 02:58:00.420410717 +0800
+++ /code/gpdb_src/src/test/regress/results/gp_parallel.out	2023-10-18 02:58:00.475410634 +0800
@@ -2036,9 +2036,11 @@
 begin;
 set local max_parallel_workers_per_gather = 8;
 select * from refresh_compare(true, false);
+NOTICE:  Non-parallel refresh duration=@ 3.283272 secs
+NOTICE:  Parallel refresh duration=@ 2.769643 secs
  parallel_is_better 
 --------------------
- t
+ f
 (1 row)
 
 select * from refresh_compare(false, false);
```

### How to reproduce

use main branch (commit id b692345b) trigger  ci/cd pipeline

### Operating System

centos x86

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by tuhaihe** [comment]
Hi @smartyhero, could you list the details here or ask for help in the internal Lark(飞书) group? Since people cannot access the `code.hashdata.xyz` in public.

**Comment by avamingli** [comment]
AFATK, this is caused by local machine performance for CI pipelines.
As a trade off,  I once add a 0.8 coefficient to workaround. 
But it still fails occasionally.

I will loosen that coefficient to pass regression.
