### ISSUE TITLE
[Bug] dispatch case failed

### ISSUE THREAD

**Issue by smartyhero** [cloudberrydb/cloudberrydb#245]
### Cloudberry Database version

PostgreSQL 14.4 (Cloudberry Database 1.0.0+5d6f0e9a24 build commit:5d6f0e9a247ffe695377867ba351f1f4db060210) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11), 64-bit compiled on Oct 18 2023 02:18:42 (with assert checking)

### What happened

trigger build cloudberrydb, build success, but icw test is failed

case name: dispatch

log
```
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /code/gpdb_src/src/test/regress/expected/dispatch.out /code/gpdb_src/src/test/regress/results/dispatch.out
--- /code/gpdb_src/src/test/regress/expected/dispatch.out	2023-10-18 15:05:14.424052181 +0800
+++ /code/gpdb_src/src/test/regress/results/dispatch.out	2023-10-18 15:05:14.449053163 +0800
@@ -870,8 +871,8 @@
 GP_IGNORE:(1 row)
 
 select * from gp_segment_configuration a, t13393 ,gp_segment_configuration b where a.dbid = t13393.tc1 limit 0;
- dbid | content | role | preferred_role | mode | status | port | hostname | address | datadir | warehouseid | tc1 | dbid | content | role | preferred_role | mode | status | port | hostname | address | datadir | warehouseid 
-------+---------+------+----------------+------+--------+------+----------+---------+---------+-------------+-----+------+---------+------+----------------+------+--------+------+----------+---------+---------+-------------
+ dbid | content | role | preferred_role | mode | status | port | hostname | address | datadir | tc1 | dbid | content | role | preferred_role | mode | status | port | hostname | address | datadir 
+------+---------+------+----------------+------+--------+------+----------+---------+---------+-----+------+---------+------+----------------+------+--------+------+----------+---------+---------
 (0 rows)
 
 SELECT gp_inject_fault('cdbcomponent_recycle_idle_qe_error', 'reset', dbid, current_setting('gp_session_id')::int)
```

[dispatch.out.log](https://github.com/cloudberrydb/cloudberrydb/files/13006169/dispatch.out.log)

### How to reproduce

checkout 5d6f0e9a247ffe695377867ba351f1f4db060210 commit

rerun dispatch case

### Operating System

centos x86 on k8s

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by roseduan** [comment]
fixed in https://github.com/cloudberrydb/cloudberrydb/pull/249
