### ISSUE TITLE
[Bug] rpt_joins case failed

### ISSUE THREAD

**Issue by smartyhero** [cloudberrydb/cloudberrydb#246]
### Cloudberry Database version

PostgreSQL 14.4 (Cloudberry Database 1.0.0+5d6f0e9a24 build commit:5d6f0e9a247ffe695377867ba351f1f4db060210) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11), 64-bit compiled on Oct 18 2023 02:18:42 (with assert checking)

### What happened

run icw test failed

case name: rpt_joins

log 
```
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /code/gpdb_src/src/test/regress/expected/rpt_joins.out /code/gpdb_src/src/test/regress/results/rpt_joins.out
--- /code/gpdb_src/src/test/regress/expected/rpt_joins.out	2023-10-18 15:06:21.490683531 +0800
+++ /code/gpdb_src/src/test/regress/results/rpt_joins.out	2023-10-18 15:06:21.543685600 +0800
@@ -2350,8 +2354,8 @@
 QUERY PLAN
 ___________
  Hash Join
-   Hash Cond: (g.dbid = rpt_issue_15860.c1)
-   ->  Seq Scan on gp_segment_configuration g
+   Hash Cond: (gp_get_segment_configuration.dbid = rpt_issue_15860.c1)
+   ->  Function Scan on gp_get_segment_configuration
    ->  Hash
          ->  Explicit Gather Motion 3:1  (slice1; segments: 3)
                ->  Insert on rpt_issue_15860
```

logfile:  [rpt_joins.out.log](https://github.com/cloudberrydb/cloudberrydb/files/13007201/rpt_joins.out.log)

### How to reproduce

use 5d6f0e9a247ffe695377867ba351f1f4db060210 commit
rerun rpt_joins case

### Operating System

centos x86 on k8s

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by avamingli** [comment]
This is caused by external_fts, our cases don't open it, but gitlab CI does. 

That's a problem @my-ship-it
