### ISSUE TITLE
cdbpath_motion_for_parallel_join() refactor

### ISSUE THREAD

**Issue by avamingli** [cloudberrydb/cloudberrydb#27]
### What happened

cdbpath_motion_for_parallel_join() has most duplicated codes with cdbpath_motion_for_join(),
we separate them for clean codes.

Some codes are not used for parallel, for example, handle update in parallel mode is meaningless.
We have a refactor for SegmentGeneralWorkers as outer side, but lack for other locus.

By reviewing the codes, some potential bugs are found. 
As this part of codes is critical, should fix them after refactor to avoid a big change.

### How to reproduce

@tuhaihe This is exactly an enhancement, but I can't find a enhancement label or remove Bug label for it.

Some fields in this template are not suite for enhancement. And I can't set assignees either.

### Operating System

no need

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by tuhaihe** [comment]
Hi @avamingli , I have helped updated your issue's label to `type: Enhancement`. The newly created issues are default labeled with `type: Bug`, only the people who have the triage privilege can update them.

/cc @my-ship-it Hi, Max, we need to redesign the org member roles for future collaborations.

**Comment by avamingli** [comment]
> Hi @avamingli , I have helped updated your issue's label to `type: Enhancement`. The newly created issues are default labeled with `type: Bug`, only the people who have the triage privilege can update them.
> 
> 
> 
> /cc @my-ship-it Hi, Max, we need to redesign the org member roles for future collaborations.

Thanks for help:)
