### ISSUE TITLE
[Bug] regress/stats test failure on external_fts

### ISSUE THREAD

**Issue by Ray-Eldath** [cloudberrydb/cloudberrydb#281]
### What happened

https://github.com/cloudberrydb/cloudberrydb/actions/runs/6730322677/job/18293680080?pr=206
<img width="764" alt="image" src="https://github.com/cloudberrydb/cloudberrydb/assets/7938763/b6931305-ab20-4c6f-93dc-d0bfae5bdfa3">

### What you think should happen instead

It's still unknown whether this failure occurs in `external_fts` only or it could happens anywhere. This test seems flaky.

### How to reproduce

No way to reliably reproduce yet.

### Operating System

ci

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by gongxun0928** [comment]
now the test has been fixed, https://github.com/cloudberrydb/cloudberrydb/actions/runs/11209843717/job/31156190398?pr=655#step:5:2424

closed
