### ISSUE TITLE
[Bug] abscissa type not supported, from sqlancer test

### ISSUE THREAD

**Issue by congxuebin** [cloudberrydb/cloudberrydb#317]
### What happened

Request to confirm if it is as designed?  
BTW, "abscissa type" is vague,  if the statement not valid,  I believe customer does not know how to fix it according to "abscissa type" error. 

`UPDATE t0 SET c0 = DEFAULT WHERE (pg_catalog.float8div('2.2946442861439234E-33'::float8, pg_catalog.interval_interval_div(('15:01:06'::time) -(pg_catalog.linear_interpolate(('true') ||('false'), pg_catalog.cash_words(CAST(1.4549639 AS money)), ('209820 day 11 hour 25 min 41 sec'::interval) +('09:05'::time), ('false') ||('true'), ('483158 day 5 hour 20 min 21 sec'::interval) +('00:56:56'::time))), '909172 day 16 hour 39 min 49 sec'::interval))) <(pg_catalog.float8(((-8521399760881100626::numeric) %(1011845922400518285::numeric)) /(pg_catalog.trunc((-5182015971170804306::numeric) ^(4186530105024981936::numeric), 465134229))));`

`ERROR:  abscissa type not supported`

### How to reproduce

CREATE TABLE t0(c0 date );

UPDATE t0 SET c0 = DEFAULT WHERE (pg_catalog.float8div('2.2946442861439234E-33'::float8, pg_catalog.interval_interval_div(('15:01:06'::time) -(pg_catalog.linear_interpolate(('true') ||('false'), pg_catalog.cash_words(CAST(1.4549639 AS money)), ('209820 day 11 hour 25 min 41 sec'::interval) +('09:05'::time), ('false') ||('true'), ('483158 day 5 hour 20 min 21 sec'::interval) +('00:56:56'::time))), '909172 day 16 hour 39 min 49 sec'::interval))) <(pg_catalog.float8(((-8521399760881100626::numeric) %(1011845922400518285::numeric)) /(pg_catalog.trunc((-5182015971170804306::numeric) ^(4186530105024981936::numeric), 465134229))));

### Operating System

centos7

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by congxuebin** [comment]
@gfphoenix78 Hi Hao,   this is the issue we talked before. I get a simple recreate today.  Thus I 'd like to use this issue for tracking this discussion.

**Comment by congxuebin** [comment]
UPDATE t0 SET c0 = DEFAULT WHERE
(pg_catalog.float8div
('2.2946442861439234E-33'::float8, pg_catalog.interval_interval_div(
    (pg_catalog.linear_interpolate(('true'), pg_catalog.cash_words(CAST(1.4549639 AS money)), 
     ('09:05'::time), ('true'), 
    ('00:56:56'::time))), '909172 day 16 hour 39 min 49 sec'::interval)))
 <0;

**Comment by gfphoenix78** [comment]
It was an unsupported type in `linterp_abscissa()`. The error is expected.

I'll close this issue. Nothing needs to do.
