### ISSUE TITLE
[Bug] Run `gpstop -m` should shutdown with mode `maintenance` instead of `smart`

### ISSUE THREAD

**Issue by tuhaihe** [cloudberrydb/cloudberrydb#334]
### Cloudberry Database version

the latest Main branch.

### What happened

When I verified the options in the CBDB Documents [gpstop](https://github.com/cloudberrydb/cloudberrydb-site/blob/cbdb-doc-validation/docs/db-utilities/db-util-gpstop.md).

For the `-m` option, it says that it will shutdown the instance with maintenance mode:
> Optional. Shuts down a Cloudberry coordinator instance that was started in maintenance mode.

But after running the cmd, the terminal shows in smart mode:

```
[gpadmin@mdw ~]$ gpstop -m
20231214:18:59:07:015158 gpstop:mdw:gpadmin-[INFO]:-Starting gpstop with args: -m
20231214:18:59:07:015158 gpstop:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20231214:18:59:07:015158 gpstop:mdw:gpadmin-[INFO]:-Obtaining CloudberryDB Coordinator catalog information
20231214:18:59:07:015158 gpstop:mdw:gpadmin-[INFO]:-Obtaining Segment details from coordinator...
20231214:18:59:07:015158 gpstop:mdw:gpadmin-[INFO]:-CloudberryDB Version: 'postgres (Cloudberry Database) 1.0.0 build dev'

Continue with coordinator-only shutdown Yy|Nn (default=N):
> y
20231214:18:59:21:015158 gpstop:mdw:gpadmin-[INFO]:-Commencing Coordinator instance shutdown with mode='smart'
20231214:18:59:21:015158 gpstop:mdw:gpadmin-[INFO]:-Coordinator segment instance directory=/data0/database/master/gpseg-1
20231214:18:59:21:015158 gpstop:mdw:gpadmin-[INFO]:-Stopping coordinator segment and waiting for user connections to finish ...
server shutting down
20231214:18:59:22:015158 gpstop:mdw:gpadmin-[INFO]:-Attempting forceful termination of any leftover coordinator process
20231214:18:59:22:015158 gpstop:mdw:gpadmin-[INFO]:-Terminating processes for segment /data0/database/master/gpseg-1
```

### What you think should happen instead

It should show that shutting down the instance in maintenance mode.

### How to reproduce

`gpstop -m`

### Operating System

CentOS Linux release 7.9.2009 (AltArch)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by tuhaihe** [comment]
For the smart mode, we can run `gpstop -M smart`.

**Comment by avamingli** [comment]
Hi, the doc said: 

> Shuts down a Cloudberry coordinator instance that was started in maintenance mode.

**that was started in maintenance mode**

How does the cluster start in your case?

**Comment by avamingli** [comment]
I test this on GP7
```shell
gpadmin@i-v3roa8c2:~/work/gp7$ gpstop -m
20231218:14:54:24:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Starting gpstop with args: -m
20231218:14:54:24:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Gathering information and validating the environment...
20231218:14:54:24:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Obtaining Greenplum Coordinator catalog information
20231218:14:54:24:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Obtaining Segment details from coordinator...
20231218:14:54:24:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 7.0.0+dev.225.g0f4cd5a9c08 build dev'

Continue with coordinator-only shutdown Yy|Nn (default=N):
> y
20231218:14:54:26:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Commencing Coordinator instance shutdown with mode='smart'
20231218:14:54:26:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Coordinator segment instance directory=/home/gpadmin/dbhouse/gp7/qddir/demoDataDir-1
20231218:14:54:26:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Stopping coordinator segment and waiting for user connections to finish ...
server shutting down
20231218:14:54:27:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Attempting forceful termination of any leftover coordinator process
20231218:14:54:27:229339 gpstop:i-v3roa8c2:gpadmin-[INFO]:-Terminating processes for segment /home/gpadmin/dbhouse/gp7/qddir/demoDataDir-1
```

Start a normal cluster then `gpstop -m`, and it shows `instance shutdown with mode='smart'`.
If you have a normal cluster and try to stop it with maintenance mode, the flag is useless and gpstop uses the default flag which is what we see 'smart'.

BUT, yes, it is definitely a risk if users do the same. 
Unpaired management operation: start a normal cluster then stop with maintenance flag, 
`gpstop -m` will shutdown the master node and left all segment nodes as zombie processes.

```shell
gpadmin@i-v3roa8c2:~/work/gp7$ gpstate -Q
20231218:15:53:48:268633 gpstate:i-v3roa8c2:gpadmin-[INFO]:-Starting gpstate with args: -Q
20231218:15:53:48:268633 gpstate:i-v3roa8c2:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 7.0.0+dev.225.g0f4cd5a9c08 build dev'
20231218:15:53:48:268633 gpstate:i-v3roa8c2:gpadmin-[CRITICAL]:-gpstate failed. (Reason='could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 7000?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 7000?
') exiting...
```
Segments process:
```shell
gpadmin@i-v3roa8c2:~/work/gp7$ pp
gpadmin   226666       1  0 14:54 ?        00:00:00 /home/gpadmin/install/gp7/bin/postgres -D /home/gpadmin/dbhouse/gp7/dbfast1/demoDataDir0 -c gp_role=execute
gpadmin   226667       1  0 14:54 ?        00:00:00 /home/gpadmin/install/gp7/bin/postgres -D /home/gpadmin/dbhouse/gp7/dbfast2/demoDataDir1 -c gp_role=execute
gpadmin   226668       1  0 14:54 ?        00:00:00 /home/gpadmin/install/gp7/bin/postgres -D /home/gpadmin/dbhouse/gp7/dbfast3/demoDataDir2 -c gp_role=execute
gpadmin   226669  226666  0 14:54 ?        00:00:00 postgres:  7002, logger process
gpadmin   226670  226667  0 14:54 ?        00:00:00 postgres:  7003, logger process
gpadmin   226673  226668  0 14:54 ?        00:00:00 postgres:  7004, logger process
gpadmin   226674  226666  0 14:54 ?        00:00:00 postgres:  7002, checkpointer
gpadmin   226676  226666  0 14:54 ?        00:00:00 postgres:  7002, background writer
gpadmin   226677  226666  0 14:54 ?        00:00:00 postgres:  7002, walwriter

........skip.......
```
I think we should report or fix&report this risk to  [Greenplum](https://github.com/greenplum-db/gpdb)

**Comment by tuhaihe** [comment]
> If you have a normal cluster and try to stop it with maintenance mode, the flag is useless and gpstop uses the default flag which is what we see 'smart'.

Hi @avamingli, thanks for your explanation. I misunderstood the doc, I thought it would shut down the cluster with maintenance mode...

I built one CBDB sandbox following this [guide](https://github.com/cloudberrydb/bootcamp/tree/main/000-cbdb-sandbox)for the documentation verification.

**Comment by avamingli** [comment]
> I think we should report or fix&report this risk to [Greenplum](https://github.com/greenplum-db/gpdb)

AFATK, I'm not sure it's a bug now...because `gpstop -m` m means master only, and it does stop master node only.
It's more like a unpaired management operation.

**Comment by tuhaihe** [comment]
Okay, I think we can close this issue now. If anyone else experiences a similar situation, we can address it at that time.
