### ISSUE TITLE
ERROR: found two entries in pg_aocsseg_73427122

### ISSUE THREAD

**Issue by liyxbeijing** [cloudberrydb/cloudberrydb#362]
### Cloudberry Database version

postgres=# select version();
version

PostgreSQL 14.4 (Cloudberry Database 1.4.0 build commit:e83e3ffc22d538deb2dbceeeae0138ca2de064e6) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Anolis 8.3.1-[5.0.1.1](http://5.0.1.1/))
, 64-bit compiled on Sep 17 2023 23:10:22 (with assert checking)

### What happened

Below errors found while doing a insert:

2024-01-10 18:11:06.142405 CST,,p88111,th1232114560,"48193",2024-01-10 17:58:10 CST,1974924,con1694,cmd4,seg48,,dx6414314,x1974925,sx2,"ERROR","XX000","found two entries in pg_aocsseg_73427122 with segno 1: ctid (0,18) and ctid (0,19) (aocssegfiles.c:194)",,,,,,"insert into xxxxxx ^M
(^M
starttime       ,^M
period  ,^M
effectiveconnmax        ,^M

connmax ",0,,"aocssegfiles.c",194,"Stack trace:
1    0xe2ea31 postgres errstart (elog.c:589)
2    0x6fd0c4 postgres <symbol not found> (aocssegfiles.c:188)
3    0x8ef474 postgres <symbol not found> (aocsam.c:957)
4    0x8f6039 postgres aocs_insert_init (discriminator 2)
5    0x8ed26f postgres <symbol not found> (ilist.h:280)
6    0x8ed4c8 postgres <symbol not found> (aocsam_handler.c:761)
7    0xa8f33c postgres <symbol not found> (nodeModifyTable.c:972)
8    0xa90173 postgres <symbol not found> (nodeModifyTable.c:2777)
9    0xa59faf postgres <symbol not found> (execProcnode.c:630)
10   0xa501db postgres <symbol not found> (execMain.c:2530)
11   0xa50c4c postgres standard_ExecutorRun (execMain.c:920)
12   0xcb0b17 postgres <symbol not found> (pquery.c:243)
13   0xcb105c postgres <symbol not found> (pquery.c:1476)
14   0xcb251f postgres PortalRun (pquery.c:970)
15   0xcab69c postgres <symbol not found> (postgres.c:1424)
16   0xcaf885 postgres PostgresMain (postgres.c:5736)
17   0xbf73f8 postgres <symbol not found> (postmaster.c:4997)
18   0xbf857e postgres PostmasterMain (postmaster.c:1658)
19   0x7c6196 postgres main (main.c:200)
20   0x7fa845f4a6a3 libc.so.6 __libc_start_main + 0xf3
21   0x7d1c0e postgres _start + 0x2e
"

### How to reproduce

repeat the insert.

### Operating System

BELinux.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by avamingli** [comment]
What's the reproduce SQL:  DDL & DML ?
