### ISSUE TITLE
[Bug] Copy from will fail when talble is ao_row

### ISSUE THREAD

**Issue by shmiwy** [cloudberrydb/cloudberrydb#364]
### What happened

```
ubuntu=# set default_table_access_method to ao_row;
ubuntu=# create table t(a bigint, b text);
ubuntu=# copy t from '/code/words.sql';
ERROR:  MPP detected 3 segment failures, system is reconnected
```

### What you think should happen instead

copy with no error

### How to reproduce

```
ubuntu=# set default_table_access_method to ao_row;
ubuntu=# create table t(a bigint, b text);
ubuntu=# copy t from '/code/words.sql';

```

### Operating System

ubuntu22

### Anything else

appendonlyam_handler.c:286 assert failed

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by avamingli** [comment]
Fixed by #365
