### ISSUE TITLE
ERROR: Make install error on Centos7.9 

### ISSUE THREAD

**Issue by Zhangbaowen-Hashdata** [cloudberrydb/cloudberrydb#383]
### What happened

Make install error on Centos7.9 during manual compilation according to readme documentation
![img_v3_028e_0152eddd-4ec1-4529-86e8-378c152b7f4g](https://github.com/cloudberrydb/cloudberrydb/assets/140392153/42951d95-ac5b-4dd0-9c5e-357cf78f0955)

### How to reproduce

Check to see if there is a problem with the file 
eg: Makefile.

### Operating System

centos7.9

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by avamingli** [comment]
Got similar issue on Ubuntu

```shell
Makefile:36: warning: overriding recipe for target 'installcheck'
Makefile:31: warning: ignoring old recipe for target 'installcheck'
/usr/bin/install: missing destination file operand after '/home/gpadmin/install/gp9/lib/python/gppylib/data/'
Try '/usr/bin/install --help' for more information.
make[4]: *** [Makefile:17: install] Error 1
make[3]: *** [Makefile:8: install-data-recurse] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:13: install-gppylib-recurse] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:7: install-bin-recurse] Error 2
make: *** [GNUmakefile:74: install] Error 2
```
@Ray-Eldath

**Comment by Ray-Eldath** [comment]
This has been resolved. with new release `v1.5.0` the tag breaks the convention of version numbers that `getversion` and many scripts dependent upon (these shouldn't be a `v` prefix). as a temporary fix, one should run `git tag -a -m "" 1.5.0 v1.5.0` after cloning the repo to forcibly correct this until a permanent fix has been carried out.

**Comment by tuhaihe** [comment]
After updating the tags, the Cloudberry Database can now be built successfully. You can try it again. @avamingli

**Comment by tuhaihe** [comment]
I believe we have resolved this issue. If not, please let us know and we will reopen it.
