### ISSUE TITLE
ERROR: Make install error on Centos7.9  after commit 20add92be713d0884ea8f8d6

### ISSUE THREAD

**Issue by Zhangbaowen-Hashdata** [cloudberrydb/cloudberrydb#418]
### What happened

make an error during manual compilation after committing 20add92be713d0884ea8f8d6, before it make is successful.

![ZMjyixvD9A](https://github.com/cloudberrydb/cloudberrydb/assets/140392153/5f31c754-2504-49eb-8c3d-a1297c69d280)

### How to reproduce

check if there are any qustions in this commit

### Operating System

centos7.9

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by Ray-Eldath** [comment]
need to install `go` after #390. maybe we should update READMEs file?

**Comment by tuhaihe** [comment]
@Zhangbaowen-Hashdata Please keep in sync with @TomShawn after you verify the new steps. Thanks.

**Comment by Zhangbaowen-Hashdata** [comment]
> @Zhangbaowen-Hashdata Please keep in sync with @TomShawn after you verify the new steps. Thanks.

OK, I will make a record

**Comment by Zhangbaowen-Hashdata** [comment]
The make has been successful by downloading Go and setting up the proxy.

**Comment by Zhangbaowen-Hashdata** [comment]
After cloning the code you can directly execute `yum install -y go` and then `export GOPROXY=https://goproxy.io,direct`
