### ISSUE TITLE
[Bug] db start failed due to gpscp not found, on external fts build

### ISSUE THREAD

**Issue by congxuebin** [cloudberrydb/cloudberrydb#468]
### Cloudberry Database version

This issue is being affected by this commit https://code.hashdata.xyz/cloudberry/database/hashdata-lightning/-/commit/17d47eca4189b64f9503b0854baaf01eef90aa50 

### What happened

**/bin/sh: gpscp: command not found**
20240611:14:35:21:014888 gpstart:i-uzvd7o05:gpadmin-[CRITICAL]:-gpstart failed. (Reason='Command 'gpscp -f /code/gpdb_src/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/config/fts_host /code/gpdb_src/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/config/cbdb_etcd.conf =:/tmp/cbdb_etcd.conf' returned non-zero exit status 127.') exiting...
20240611:14:35:21:008724 gpinitsystem:i-uzvd7o05:gpadmin-[WARN]:
20240611:14:35:21:008724 gpinitsystem:i-uzvd7o05:gpadmin-[WARN]:-Failed to start CloudberryDB instance; review gpstart output to
20240611:14:35:21:008724 gpinitsystem:i-uzvd7o05:gpadmin-[WARN]:- determine why gpstart failed and reinitialize cluster after resolving
20240611:14:35:21:008724 gpinitsystem:i-uzvd7o05:gpadmin-[WARN]:- issues.  Not all initialization tasks have completed so the cluster
20240611:14:35:21:008724 gpinitsystem:i-uzvd7o05:gpadmin-[WARN]:- should not be used.
20240611:14:35:21:008724 gpinitsystem:i-uzvd7o05:gpadmin-[WARN]:-gpinitsystem will now try to stop the cluster

### How to reproduce

rpm -ivh http://cbdb-repository.obs.cn-north-4.myhuaweicloud.com/cbdb/centos7/x86_64/release/1.x/rpms/hashdata-lightning-1.5.4%2Bdev.27.gd4a8b246-1.el7.x86_64-76834-release-external_fts.rpm
no gpscp found

### Operating System

centos7

### Anything else

Tried rename gpsync to gpscp,  then source /usr/local/cloudberry-db-devel/greenplum_path.sh,  then db could be started successfully. 

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by tuhaihe** [comment]
AFAI, we now replace gpscp with gpsync https://github.com/cloudberrydb/cloudberrydb/pull/430 ,FYI

**Comment by congxuebin** [comment]
@tuhaihe Thanks for the information,  yes, I saw that.  But db start failed due to this on certain build, which is the issue need to be resolved.

**Comment by congxuebin** [comment]
Thanks for the fix.  The issue is gone.
