### ISSUE TITLE
[Bug] I have installed successfully cloudberry on RHEL 9  but when initiating my cluster it fails

### ISSUE THREAD

**Issue by tuhaihe** [cloudberrydb/cloudberrydb#475]
I have installed successfully cloudberry on RHEL 9  but when initiating my cluster it fails with:

```
20240618:22:19:54:246202 gpstop:gacsgpopsmaster01:gpadmin-[CRITICAL]:-gpstop failed. (Reason='module 'pgdb' has no attribute 'OperationalError'') exiting..
```

When I initiate the cluster demo in 1 node was ok but not this one. with 4 datanodes. Do you know how to solve this error?

> This issue is created from Slack thread.

**Comment by pdteodoro** [comment]
We have solved the issue uninstalling gpdb and only using PysgreSQL.
Thanks,
Pilar

**Comment by gfphoenix78** [comment]
@tuhaihe Is this issue done?
