### ISSUE TITLE
[Bug] `configure` development script generates an 'sh' shell error due to an initialized variable (ac_cv_func_fseeko)

### ISSUE THREAD

**Issue by edespino** [cloudberrydb/cloudberrydb#516]
### Cloudberry Database version

main (HEAD)

### What happened

The following sh scripting error (unary operator expected) is seen when `configure` is run:

```
checking for __crc32cb, __crc32ch, __crc32cw, and __crc32cd with CFLAGS=-march=armv8-a+crc... no
checking which CRC-32C implementation to use... SSE 4.2
./configure: line 21391: test: =: unary operator expected
checking size of off_t... (cached) 8
checking for library containing sem_init... none required

```

### What you think should happen instead

The missing variable `ac_cv_func_fseeko` should be defined and the error should not happen.

### How to reproduce

Simply run `configure` script.

### Operating System

Platform independent (reproduced on Rocky Linux 9.4)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by gfphoenix78** [comment]
Hi @edespino , the variable `ac_cv_func_fseeko` is not set by the macro `AC_FUNC_FSEEKO`. The pg upstream has fixed this issue. I opened a PR to align the code with pg upstream.
