### ISSUE TITLE
[Bug] brin index related,  could not read block xxx in file  when insert after cbdb binary swap

### ISSUE THREAD

**Issue by congxuebin** [cloudberrydb/cloudberrydb#558]
### Cloudberry Database version

 Swap from: PostgreSQL 14.4 (Cloudberry Database 1.6.0 build 79708 commit:81b10d5c)
 Swap to: PostgreSQL 14.4 (Cloudberry Database 1.6.0+dev.3.g48d76a3e build 80152 commit:48d76a3e)

### What happened

psql:test.sql:38: ERROR:  could not read block 16384 in file "base/16384/24584": read only 0 of 32768 bytes  (seg2 127.0.0.1:7004 pid=5195)

### How to reproduce

Download this file: [recreate_script.zip](https://github.com/user-attachments/files/16517506/recreate_script.zip)
Unzip the recreate_script.zip
Install cbdb: PostgreSQL 14.4 (Cloudberry Database 1.6.0 build 79708 commit:81b10d5c)
Then install another cbdb:  PostgreSQL 14.4 (Cloudberry Database 1.6.0+dev.3.g48d76a3e build 80152 commit:48d76a3e)
Issue the source command: source /code/cbdb_src/gpAux/gpdemo/gpdemo-env.sh
Run recreate.sh 

### Operating System

centos7

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by congxuebin** [comment]
Hi Mingli,
According to information in release meeting, it is needed ensure compatibility across certain versions. I'd like to open an issue regarding this. If you have any concerns about binary compatibility requirement, would you please work with Max on this?

**Comment by avamingli** [comment]
> Hi Mingli, According to information in release meeting, it is needed to ensure compatibility across certain versions. I'd like to re-open this issue regarding this. If you have any concerns about binary compatibility requirement, would you please work with Max on this?

No objection if release team decide to do that work, thanks.

**Comment by my-ship-it** [comment]
Already discussed. It's Lightning related, and it's not an issue but expected.
