### ISSUE TITLE
[Bug] data queried from external table defined with error limit unexpected change

### ISSUE THREAD

**Issue by congxuebin** [cloudberrydb/cloudberrydb#573]
### Cloudberry Database version

 PostgreSQL 14.4 (Cloudberry Database 1.0.0+ed64982 build commit:ed64982034245e8b46926b75f349a4a5d5b8fd67) 

### What happened

Testrepo testcase failed:  
ErrorLogTests.test_limit ... 644.98 ms ... FAIL 

It is related to this PR, https://github.com/cloudberrydb/cloudberrydb/pull/320

DDL
```
CREATE EXTERNAL TABLE exttab_limit_1( i int, j text ) 
LOCATION ('gpfdist://localhost:8080/exttab_limit_1.tbl') FORMAT 'TEXT' (DELIMITER '|') 
LOG ERRORS SEGMENT REJECT LIMIT 10;
CREATE EXTERNAL TABLE
-- Generate the file with lot of errors
\! python3 /code/cbdb_testrepo_src/mpp/gpdb/tests/queries/basic/exttab/errlog/sql/datagen.py 200 50 > /code/cbdb_testrepo_src/mpp/gpdb/tests/queries/basic/exttab/errlog/data//exttab_limit_2.tbl
-- reaches reject limit, use the same err table
CREATE EXTERNAL TABLE exttab_limit_2( i int, j text ) 
LOCATION ('gpfdist://localhost:8080/exttab_limit_2.tbl') FORMAT 'TEXT' (DELIMITER '|') 
LOG ERRORS SEGMENT REJECT LIMIT 2;
CREATE EXTERNAL TABLE
-- Test: LIMIT queries without segment reject limit reached
-- Note that even though we use exttab_limit_2 here , the LIMIT 3 will not throw a segment reject limit error
-- order 0
```

Query expected result:
```
with cte1 as 
(
SELECT e1.i, e2.j FROM exttab_limit_1 e1, exttab_limit_1 e2
WHERE e1.i = e2.i LIMIT 5
)
SELECT * FROM cte1, exttab_limit_2 e3 where cte1.i = e3.i LIMIT 3;
psql:/code/cbdb_testrepo_src/mpp/gpdb/tests/queries/basic/exttab/errlog/output/limit_planner.sql:33: NOTICE:  found 5 data formatting errors (5 or more input rows), rejected related input data
 i |    j     | i |    j     
---+----------+---+----------
 0 | 0_number | 0 | 0_number
 1 | 1_number | 1 | 1_number
 5 | 5_number | 5 | 5_number
(3 rows)
```
Query actual result:
```
with cte1 as 
(
SELECT e1.i, e2.j FROM exttab_limit_1 e1, exttab_limit_1 e2
WHERE e1.i = e2.i LIMIT 5
)
SELECT * FROM cte1, exttab_limit_2 e3 where cte1.i = e3.i LIMIT 3;
psql:/code/cbdb_testrepo_src/mpp/gpdb/tests/queries/basic/exttab/errlog/output/limit_planner.sql:33: NOTICE:  found 5 data formatting errors (5 or more input rows), rejected related input data
 i |    j     | i |    j     
---+----------+---+----------
 0 | 0_number | 0 | 0_number
 1 | 1_number | 1 | 1_number
 4 | 4_number | 4 | 4_numbe
(3 rows)
```

### How to reproduce

goto testrepo folder:
```
cd  /code/cbdb_testrepo_src/
```
run testrepo testcase to reproduce:
```
/code/cbdb_testrepo_src/test_framework/tinc.py discover /code/cbdb_testrepo_src/mpp/gpdb/tests/queries/basic/exttab/errlog
```

### Operating System

centos7

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by avamingli** [comment]
Offhand, I don't think it's a bug. 
> SELECT * FROM cte1, exttab_limit_2 e3 where cte1.i = e3.i LIMIT 3;

SQL standard doesn't guarantee the results with only LIMIT.
The SQL doesn't have ORDER BY, if you have more than 3 rows,  the results is uncertain  with only LIMIT.

See https://www.postgresql.org/docs/14/queries-limit.html
> When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows.

**Comment by congxuebin** [comment]
Anyway,  after looking into the case,  actual result now makes more sense than before. 

```
 i |    j     | i |    j     
---+----------+---+----------
 0 | 0_number | 0 | 0_number
 1 | 1_number | 1 | 1_number
 4 | 4_number | 4 | 4_numbe
(3 rows)
 
```

The test case is bad.  I can add a sort to the query within CTE to make the result more stable.  Even though in this way data result is not 100% guaranteed. If it failed again,  we can figure out another solution.  Please let me know if you have different thoughts. Thanks.

```
with cte1 as
(
SELECT e1.i, e2.j FROM exttab_limit_1 e1, exttab_limit_1 e2
WHERE e1.i = e2.i ORDER BY e1.i ASC LIMIT 5
)
SELECT * FROM cte1, exttab_limit_2 e3 where cte1.i = e3.i LIMIT 3;
```

**Comment by congxuebin** [comment]
Resolved it by adjusting test case.  

ErrorLogTests.test_limit ... 675.91 ms ... ok
