### ISSUE TITLE
Catalog changes between minor releases? 

### ISSUE THREAD

**Issue by reshke** [cloudberrydb/cloudberrydb#580]
### Cloudberry Database version

after this PR https://github.com/cloudberrydb/cloudberrydb/pull/531

recompiling CBDB binaries leads to restart error: 
```
20240820:09:38:31:004650 gpstart:yezzey-bionic:reshke-[INFO]:-Catalog Version of coordinator directory incompatible with binaries
20240820:09:38:31:004650 gpstart:yezzey-bionic:reshke-[ERROR]:-gpstart error: Catalog Versions are incompatible
```

I want to know the policy for catalog changes in CBDB. How do existing client handle changes like this?

### What happened

-

### How to reproduce

gpstop -a -i && gpstart -a

### Operating System

any

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by avamingli** [comment]
Right,  see https://github.com/cloudberrydb/cloudberrydb/pull/560#issuecomment-2272897518
Another reason is Cherry-pick project.
The catalog is changed even across path versions.
We can't guarantee catalog compatible or binary swap until we are ready for a stable version.
You may need to re-config/re-import data if there were such problems.

**Comment by reshke** [comment]
> Yes, see [#560 (comment)](https://github.com/cloudberrydb/cloudberrydb/pull/560#issuecomment-2272897518) Another reason is Cherry-pick project. The catalog is changed even across path versions. We can't guarantee catalog compatible or binary swap until we are ready for a stable version. You may need to re-config/re-import data if there were such problems.

So, releases published in repo are not stable? When we can expect stable version (would in happen in 2025 for example)?
 re-importing data is very long process for big deployments. Im thinking of starting support for pg_upgrade for CBDB by myself...

**Comment by avamingli** [comment]
> So, releases published in repo are not stable? When we can expect stable version (would in happen in 2025 for example)?

Not sure, CBDB is iterating fast, there will be many features requiring catalog change. 
And we're working on cherry-pick internal codes to CBDB that another round of catalog changes will come soon.

**Comment by tuhaihe** [comment]
@reshke could you join the community slack channel [#cbdb-release-plan](https://cloudberrydb.slack.com/archives/C07HL11F5GB) via the [iniviation link](https://communityinviter.com/apps/cloudberrydb/welcome)? We're talking about the new release policy here, welcome to have your feedback.
