### ISSUE TITLE
[Bug] volatile EquivalenceClass has no sortref

### ISSUE THREAD

**Issue by shmiwy** [cloudberrydb/cloudberrydb#593]
### What happened

ERROR:  volatile EquivalenceClass has no sortref.

### How to reproduce

CREATE TABLE t0(c0 bigserial  PRIMARY KEY) USING heap WITH (autovacuum_vacuum_threshold=1468046284, autovacuum_analyze_threshold=1889118206, autovacuum_vacuum_cost_delay=9, fillfactor=25, autovacuum_freeze_max_age=1860760049, autovacuum_enabled=0, autovacuum_freeze_min_age=402702412, autovacuum_vacuum_cost_limit=2500);
CREATE TABLE IF NOT EXISTS t1(LIKE t0);

CREATE TABLE IF NOT EXISTS t2(LIKE t0 INCLUDING INDEXES);
CREATE UNLOGGED TABLE IF NOT EXISTS t3(LIKE t2);
CREATE TEMPORARY TABLE IF NOT EXISTS t4(LIKE t3);

CREATE TABLE IF NOT EXISTS t5(LIKE t2);

SELECT '100.147.127.36' FROM t1, ONLY t2, t4* CROSS JOIN t0* CROSS JOIN ONLY t3 GROUP BY pg_jit_available() HAVING inet_same_family('148.199.107.23', '214.26.36.61') UNION ALL SELECT '100.147.127.36' FROM t1*, ONLY t2, t4* CROSS JOIN t0* CROSS JOIN ONLY t3 GROUP BY pg_jit_available() HAVING NOT (inet_same_family('148.199.107.23', '214.26.36.61')) UNION ALL SELECT '100.147.127.36' FROM t1*, ONLY t2, t4* CROSS JOIN t0 CROSS JOIN ONLY t3 GROUP BY pg_jit_available() HAVING (inet_same_family('148.199.107.23', '214.26.36.61')) ISNULL;

### Operating System

ubuntu22

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by avamingli** [comment]
Orca will fallback to legacy planner, so the problem is certain for both.
