### ISSUE TITLE
[Bug] The current HEAD of main no longer builds on Rocky Linux 8 & 9.

### ISSUE THREAD

**Issue by edespino** [cloudberrydb/cloudberrydb#668]
### Cloudberry Database version

Cloudberrydb main branch (fdc5abc0ca)

### What happened

Compilation error:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3 -fPIC  -DUSE_INTERNAL_FTS=1  -Werror=uninitialized -Werror=implicit-function-declaration -Werror -I../../../../src/interfaces/libpq -I../../../../src/include   -D_GNU_SOURCE -I/usr/include/libxml2   -c -o appendonlyam.o appendonlyam.c
appendonlyam.c: In function ‘appendonly_insert’:
appendonlyam.c:3052:9: error: unused variable ‘firstSequence’ [-Werror=unused-variable]
   int64 firstSequence = GetFastSequences(aoInsertDesc->segrelid,
         ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

### What you think should happen instead

This is a relatively new issue. I am able to build at `781c43b63b`.

### How to reproduce

Following the documentation: For RHEL 8 and Rocky Linux 8 (https://cloudberrydb.org/docs/cbdb-linux-compile).

```
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/cloudberrydb
make
```

### Operating System

Rocky Linux 8 & 9

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by my-ship-it** [comment]
Thanks for reporting the issue, Ed! We will have a look.
How about we support Rocky Linux 8 & 9 in our CI to avoid this in future?

**Comment by edespino** [comment]
> Thanks for reporting the issue, Ed! We will have a look. How about we support Rocky Linux 8 & 9 in our CI to avoid this in future?

I will look into this ASAP.

**Comment by yihong0618** [comment]
yes rocky9 failed too
