### ISSUE TITLE
[Bug] hot standby, with remote_apply level, it will cause dead lock in test_repo

### ISSUE THREAD

**Issue by tuhaihe** [cloudberrydb/cloudberrydb#73]
### Cloudberry Database version

main

### What happened

with the remote_apply level of synchronous_commit, enable hot_standby.
Query the table on the standby while altering the table on the master it may cause deadlock.

### How to reproduce

```
/home/gpadmin/workspace/cbdb_testrepo/test_framework/tinc.py discover mpp/common
GPToolKit.test_concurrent_heap
```

### Operating System

Default

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by my-ship-it** [comment]
Close it, it's a internal SPIKE.
The related SPIKE doc: https://hashdata.feishu.cn/docx/DXJkd6FDYopxYpxN8nNc0IUAnsh
