### ISSUE TITLE
Refine the logic of Fts log on CBDB

### ISSUE THREAD

**Issue by my-ship-it** [cloudberrydb/cloudberrydb#89]
Now, the print logic of cbdb_log seemly is of redundancy. We can try to complete with `vfprintf` instead of `fprintf`.

**Comment by ruhuang2001** [comment]
Hi, I would llike to fix this issue! I have submitted a pull request, but not sure if I have understood the issue correctly. Could you please take a look at my PR to see if there are any areas that still need modification?

**Comment by tuhaihe** [comment]
@ruhuang2001 thanks for your pull request. The team will review your contribution ASAP.
